### ISSUE TITLE
Epic: Design

### ISSUE THREAD

**Issue by katty-bird** [katty-bird/sports-fields#6]
Develop Design System for the Application
logo, color palette, icons, cards, personal account

**Comment by hientptran** [comment]
## Stand 21.06
- [Figma-Wireframe](https://www.figma.com/design/bLkWunMLrQmdlINvXG5sih/Sport-fields-app?node-id=7603-13285&t=87yM3kk7WS3tlALm-1)

### To-dos:
- [ ] Unnötige Features entfernen
- [ ] User-Journey und relevante Features festlegen
